development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: 'plain'
  :user_name: iwantyouget@gmail.com
  :password: a1s2d3f4g5h6j7k8l90
  :enable_starttls_auto: true
test:
  :address: mail.heavenseven.net
  :port: 25
  :domain: www.heavenseven.net
  :authentication: plain
  :user_name: iwyg+heavenseven.net
  :password: r1NmhzzisQw9
  :enable_starttls_auto: false
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: 'plain'
  :user_name: iwantyouget@gmail.com
  :password: a1s2d3f4g5h6j7k8l90
  :enable_starttls_auto: true
