development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: 'plain'
  :user_name: 'username@gmail.com'
  :password: 'secret'
  :enable_starttls_auto: true
  :openssl_verify_mode: 'none'
test:
  :address: smtp.gmail.com
  :port: 587
  :authentication: 'plain'
  :user_name: 'username@gmail.com'
  :password: 'secret'
  :enable_starttls_auto: true
  :openssl_verify_mode: 'none'
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: 'plain'
  :user_name: 'username@gmail.com'
  :password: 'secret'
  :enable_starttls_auto: true
  :openssl_verify_mode: 'none'
