# itemtypes
itemtypes: ["good", "transport", "service", "sharingpoint", "knowledge", "skill"]

# count of max. objects in index view 
items:
  per_page: 24
  related_per_page: 6
users:
  per_page: 24
groups:
  per_page: 24
pings:
  per_page: 30

# mailer
mailer:
  # default mailer css
  css: :mailer
  charset: UTF-8

# facebook authentication
fb_key: 183760235163626
fb_secret: fb4d6c2c0fc10cf276ef2b14b8203615

# google
google:
  analytics_id: UA-XXXXXXXX-X

# time/date format
time:
  date_formats:
    default: "%B %d, %Y"
    mailbox: "%A, %B %d, %Y"
    forms: "%d.%m.%Y %H:%M"

## model based settings

# user

# item
item:
  visible_for:
    default: all
    values: ['all', 'members',  'me']
# ping
ping:
  visible_for:
    default: owner
    values: ['all', 'members', 'owner', 'me']
# group
group:
  visible_for:
    default: all
    values: ['all', 'members', 'me']
# meetup
meetup:
  visible_for:
    default: owner
    values: ['all', 'members', 'me']

